spring.application.name=spring-ai-mcp
server.port=8085

spring.ai.openai.base-url=https://api-inference.modelscope.cn
spring.ai.openai.api-key=ms-2fac3058-9416-4f3a-947e-b562d84c1178
spring.ai.openai.chat.options.model=Qwen/Qwen3-30B-A3B-Thinking-2507
spring.main.web-application-type=servlet

# Spring AI配置
spring.ai.retry.max-attempts=3

# 数据库配置
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=spring_ai
spring.datasource.password=spring_mcp
spring.h2.console.enabled=true

# Liquibase配置
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# MyBatis-Plus配置
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type=auto

# 设置超时
spring.webflux.client.response-timeout=60s

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.initialized=true
spring.ai.mcp.client.request-timeout=30s
#mcp 相关配置
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.toolcallback.enabled=true
#mcp 服务器
# sequentialthinking mcp
spring.ai.mcp.client.sse.connections.sequentialthinking.url=https://mcp.api-inference.modelscope.net
spring.ai.mcp.client.sse.connections.sequentialthinking.sse-endpoint=/a8c87baf4dfb49/sse

# 高德amap-maps mcp
spring.ai.mcp.client.sse.connections.amap-maps.url=https://mcp.api-inference.modelscope.net
spring.ai.mcp.client.sse.connections.amap-maps.sse-endpoint=/ad3955f43ecd4a/sse

# 配置mcp
#spring.ai.mcp.client.sse.connections.test.url=http://localhost:8005
#spring.ai.mcp.client.sse.connections.test.sse-endpoint=/test/sse


# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.ai.mcp=WARN
logging.level.org.springframework.ai.mcp.client.transport.SseClientTransport=INFO
logging.level.com.springboot.springai.mcpClient=INFO
logging.level.io.modelcontextprotocol.client=WARN
logging.level.io.modelcontextprotocol.spec=WARN


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path= /swagger-ui.html

knife4j.enable= true
knife4j.production=false
knife4j.basic.enable=false

