spring.application.name=spring-ai-mcp
server.port=8082


spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api-inference.modelscope.cn
spring.ai.openai.chat.options.model=Qwen/Qwen3-30B-A3B-Thinking-2507
spring.ai.retry.max-attempts=1
